version: '3.1'

services:

  mongo:
    container_name: my-mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root11
      MONGO_INITDB_ROOT_PASSWORD: 371root1124
    ports:
      - 27017:27017

# docker-compose -f docker-mongo.yml up -d


#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#      ME_CONFIG_BASICAUTH: false